export const errorCodes = [
  "AUTH_TOKEN_INVALID", "FORBIDDEN_ROLE", "CONSENT_REQUIRED", "PLATE_ALREADY_REGISTERED",
  "SLOT_UNAVAILABLE", "CAPACITY_EXCEEDED", "ENTITLEMENT_EXHAUSTED", "SUBSCRIPTION_LOCKED_IN",
  "SUBSCRIPTION_SUSPENDED", "ROADSIDE_NOT_ELIGIBLE", "OUT_OF_SERVICE_ZONE", "INSPECTION_INCOMPLETE",
  "INSPECTION_IMMUTABLE", "NOT_CERTIFIED_TECHNICIAN", "ODOMETER_REGRESSION", "APPROVAL_REQUIRED",
  "CERTIFICATE_REVOKED", "PAYMENT_FAILED", "DUPLICATE_REQUEST", "RATE_LIMITED",
  "IDEMPOTENCY_KEY_REQUIRED", "SUBSCRIPTION_ALREADY_ACTIVE", "SUBSCRIPTION_NOT_UPGRADE",
  "SUBSCRIPTION_NOT_DOWNGRADE",
] as const;
export type ErrorCode = (typeof errorCodes)[number];
